### PR TITLE
add space between two words

### PR DESCRIPTION
**Pull request by drmperez**

### CODE REVIEW

**Comment by edoapra** [comment]
@drmperez your patch cannot be merged since you are 100 commits behind master
I will try to merge it manually.
Does this sound OK for you?

**Comment by edoapra** [comment]
@drmperez By the way, after inspecting the patch, I do not see any difference other than white-spaces that have no effect on the markdown display. Could you please correct me if I am wrong?

**Comment by drmperez** [comment]
@edoapra I was trying to add a space between "approximations" and "for" (underlined in image). 
markdown

**Comment by edoapra** [comment]
@drmperez  found it now. I was looking at the wrong place.
Sorry about this

**Comment by drmperez** [comment]
@edoapra No worries. Thanks!

**Comment by edoapra** [comment]
The changes to Ccca.md were wrong.
The CCCA method is in CCCA.md
I removed that part of the commit

**Comment by drmperez** [comment]
Oh sorry - that was an accident. Thanks!

**Pull request merged**
